In [ ]:
import sqlite3
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

In [2]:
conn=sqlite3.connect('hims.db')

In [ ]:
cur=conn.cursor()
cur.execute("""
UPDATE patients
SET fullname = ?,
    age = ?,
    gender = ?,
    email = ?
WHERE rowid = (SELECT rowid FROM patients ORDER BY rowid LIMIT 1)
""", ('Sana Bhatia', 20, 'Female', 'sana@gmail.com'))
conn.commit()

In [4]:
df=pd.read_sql_query('select* from patients ;',conn)
df

,patient_id,fullname,dob,age,gender,marital_status,mobile,email,aadhaar,address,...,family_history,has_insurance,insurance_provider,policy_number,insurance_validity,department,preferred_doctor,appointment_date,appointment_time,created_at
0,PAT20260608084220,kunal,30121995,30,male,single,8860065479,kunal.rwd@gmail.com,123456789101,267,...,no,no,,,,cardiology,rakesh,08-06-2026,02:00,2026-06-08 08:42:20
1,PAT20260812134601,raam,1995-12-1,31,male,married,8860065479,kunal.rwd@gmail.com,999999999999,267,...,sigar and bp,yes,aditya birla,9999999999,2026-12-08,physiology,madan,no,no,2026-08-12 13:46:01
2,PAT20260824135034,Hari Prasad,1995-12-30,30,male,single,9999999999,k@gmail.com,123456789101,121,...,no,no,,,,physician,madan,2026-08-10,12:00,2026-08-24 13:50:34

In [5]:
total_patients=df['patient_id'].nunique()
total_patients

3

In [6]:
Min_age=df['age'].min()
Max_age=df['age'].max()
Avg_age=df['age'].mean()

In [18]:
Gdf=pd.DataFrame(df['gender'].value_counts()).reset_index()

In [19]:
Gdf

  gender  count
0   male      3

In [20]:
fig=px.bar(Gdf,color='gender')
fig.show()

In [14]:
GMDF=df.groupby(['gender','marital_status']).agg({'patient_id' : 'nunique'}).reset_index()

In [21]:
GMDF

  gender marital_status  patient_id
0   male        married           1
1   male         single           2

In [10]:
px.bar(GMDF,x='gender',y='patient_id',color='marital_status')

In [22]:
px.bar(df.groupby('has_insurance').agg({'patient_id' : 'nunique'}))

In [23]:
doctor=df.groupby(
    ['department','preferred_doctor']).agg(
        {'patient_id':'nunique'}).reset_index()
doctor

   department preferred_doctor  patient_id
0  cardiology           rakesh           1
1   physician            madan           1
2  physiology            madan           1

In [ ]:
px.bar(doctor,x='department',y='patient_id',color='preferred_doctor')

: